apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsakbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsakbuggy
  template:
    metadata:
      labels:
        app: devopsakbuggy
    spec:
      containers:
      - name: devopsakbuggy
        image: 871395277524.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsakbuggy
    k8s-app: devopsakbuggy
  name: devopsakbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: devopsakbuggy
